### ISSUE TITLE
Your code does not work

### ISSUE THREAD

**Issue by whulizhen** [sasamil/Quartic#1]
I computed the solutions from your code and compared with what I got from Matlab. They appeared to be different. So I think your code may have bugs.

**Comment by sasamil** [comment]
Could you please give me an example (or few examples) with this issue. I will check it.

Thank you for pointing out to me the problem.

Regards!

**Comment by sasamil** [comment]
Could you please provide an example with 'wrong' results? I'd like to check it.

Thanks & Regards!

**Comment by whulizhen** [comment]
I know your algorithm should be fine in theory. I also wrote a function to solve the quartic using your cubic solver (it seems your cubic solver works). see https://github.com/whulizhen/PPM_atm_shadow_function.git

**Comment by sasamil** [comment]
Do you think I can close the issue?

Thanks & Regards!

**Comment by whulizhen** [comment]
Yes, I think I do not have problems any more. Thanks for your code!

**Comment by sasamil** [comment]
All the best with your code, Whulizhen! The issue is going to be closed.
